config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  resources :gardens, only: [:show] do
    resources :plants, only: [:create]
  end

  resources :plants, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants
  # has_many :gardeners, through: :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  # rails g model Plant garden:references nous donne gratos le belongs_to :garden
  belongs_to :garden

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def show
    @plant  = Plant.new
    @garden = Garden.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @gardens = Garden.all
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def create
    # 1. Initialize plant with strong params
    @plant = Plant.new(plant_params)

    # 2. Get back correct garden to link plant with (thanks to params[:garden_id])
    @garden = Garden.find(params[:garden_id])

    # 3. Link une plante à son garden
    @plant.garden = @garden

    # 4. Save
    if @plant.save
      # if ça a fonctionné => redirige vers gardens#show
      redirect_to garden_path(@garden)
    else
      # else               => render :new
      render 'gardens/show'
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy

    redirect_to garden_path(@plant.garden)
  end

  private
  def plant_params
    params.require(:plant).permit(:name, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_picture_url %>);">
  <div class="container p-5">
    <h1><%= @garden.name %></h1>
    <% if @garden.plants.any? %>
      <div class="banner-spotlight banner-spotlight-right banner-spotlight-success">
        <strong><%= @garden.plants.count %> plants</strong> growing strong here 💪
      </div>
    <% else %>
      <div class="banner-spotlight banner-spotlight-right banner-spotlight-warning" role="alert">
        <span>There are <strong>no plants</strong> yet 😢</span>
      </div>
    <% end %>
  </div>
</div>

<div class="d-flex mt-2 p-5 align-items-top">
  <div class="cards mr-3 flex-grow-1">
    <% @garden.plants.each do |plant| %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= plant.picture_url %>)">
        <%= plant.name %>

        <%= link_to plant_path(plant), method: :delete, class: 'remove-link', data: {confirm: 'Are you sure you want to remove this plant from the garden?'} do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    <% end %>
  </div>
  <%= simple_form_for([@garden, @plant], html: { class: 'flex-grow-1' }) do |f| %>
    <%= f.input :name %>
    <%= f.input :picture_url %>

    <%= f.button :submit, class: 'btn btn-success float-right' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Rendering de partial HTML / ERB -->
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container mt-5">
  <h1>Welcome to Gardens & Plants application</h1>

  <div class="cards mt-5 flex-grow-1">
    <% @gardens.each do |garden| %>
      <%= link_to garden_path(garden) do %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= garden.banner_picture_url %>)">
          <%= garden.name %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/cveneziani", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>